# Generated by Django 5.1.4 on 2024-12-25 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('interval', models.CharField(choices=[('minutes', 'Minutes'), ('hourly', 'Hourly'), ('daily', 'Daily')], max_length=50)),
                ('kpi_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimulatorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('attribute_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim_app.simulator')),
            ],
        ),
    ]
